/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#3c4a3d",
        "surface-bright": "#f3fcef",
        "tertiary-fixed-dim": "#ffb59b",
        "outline-variant": "#bbcbb9",
        "on-primary": "#ffffff",
        "secondary-container": "#a5ede0",
        "on-secondary-fixed-variant": "#005047",
        "on-secondary-fixed": "#00201c",
        "primary-fixed-dim": "#3de273",
        "outline": "#6c7b6b",
        "on-tertiary-fixed": "#380d00",
        "primary-fixed": "#66ff8e",
        "on-primary-fixed-variant": "#005322",
        "on-secondary": "#ffffff",
        "surface-container": "#e7f1e4",
        "error": "#ba1a1a",
        "inverse-surface": "#2a332a",
        "on-secondary-container": "#226e63",
        "tertiary-fixed": "#ffdbcf",
        "on-surface": "#151e16",
        "on-background": "#151e16",
        "primary-container": "#25d366",
        "error-container": "#ffdad6",
        "background": "#f3fcef",
        "secondary": "#1c695f",
        "on-tertiary-container": "#78351b",
        "inverse-on-surface": "#eaf3e6",
        "surface-dim": "#d3ddd0",
        "primary": "#006d2f",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#763319",
        "surface-container-low": "#edf6e9",
        "on-primary-fixed": "#002109",
        "surface-container-high": "#e2ebde",
        "on-error": "#ffffff",
        "inverse-primary": "#3de273",
        "on-primary-container": "#005523",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#a8f0e3",
        "surface-container-highest": "#dce5d8",
        "secondary-fixed-dim": "#8cd4c7",
        "surface": "#f3fcef",
        "tertiary": "#93492e",
        "surface-variant": "#dce5d8",
        "surface-tint": "#006d2f",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#ffa07e",
        "chat-sent": "#D9FDD3",
        "chat-received": "#FFFFFF",
        "panel-border": "#E9EDEF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        xl: "32px",
        "panel-sidebar": "320px",
        sm: "8px",
        "max-bubble-width": "65%",
        "panel-customer": "360px",
        md: "16px",
        xs: "4px",
      },
      fontFamily: {
        "h1": ["Inter", "sans-serif"],
        "chat-text": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "chat-text": ["15px", { lineHeight: "21px", fontWeight: "400" }],
        "h2": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      boxShadow: {
        surface: "0px 2px 4px rgba(11, 20, 26, 0.08)",
        overlay: "0px 6px 12px rgba(11, 20, 26, 0.12)",
      },
    },
  },
  plugins: [],
};
