// Dummy data for testing the UI — remove when connecting to real API

export const dummyConversations = [
  {
    _id: 'conv_001',
    customerName: 'Sarah Jenkins',
    customerPhone: '+1 (415) 555-0234',
    lastMessage: 'Yes, the enterprise plan looks perfect for our needs. Can we discuss the SLA?',
    lastMessageTime: new Date().toISOString(),
    unreadCount: 2,
    status: 'hot_lead',
    aiEnabled: true,
    assignedAdmin: { name: 'Alex' },
    customer: {
      customerName: 'Sarah Jenkins',
      customerPhone: '+1 (415) 555-0234',
      businessName: 'Globex Corp',
      email: 's.jenkins@globex.corp',
      website: 'www.globex.corp',
      tags: ['Enterprise', 'High Priority'],
      notes: 'Customer requested SLA details and whitepaper for 500-seat enterprise deployment.',
    },
  },
  {
    _id: 'conv_002',
    customerName: 'TechVision Corp',
    customerPhone: '+1 555-0198',
    lastMessage: 'We will review the invoice and get back to you.',
    lastMessageTime: new Date(Date.now() - 86400000).toISOString(), // yesterday
    unreadCount: 0,
    status: 'open',
    aiEnabled: true,
    assignedAdmin: { name: 'Maria' },
    customer: {
      customerName: 'TechVision Corp',
      customerPhone: '+1 555-0198',
      businessName: 'TechVision Inc.',
      email: 'billing@techvision.io',
      website: 'techvision.io',
      tags: ['SMB', 'Billing'],
      notes: 'Awaiting invoice review from their finance team.',
    },
  },
  {
    _id: 'conv_003',
    customerName: 'David Chen',
    customerPhone: '+1 (628) 555-0142',
    lastMessage: 'Here is the signed contract.',
    lastMessageTime: new Date(Date.now() - 2 * 86400000).toISOString(), // 2 days ago
    unreadCount: 0,
    status: 'closed',
    aiEnabled: false,
    assignedAdmin: { name: 'Alex' },
    customer: {
      customerName: 'David Chen',
      customerPhone: '+1 (628) 555-0142',
      businessName: 'Chen & Associates',
      email: 'david@chenassoc.com',
      website: 'chenassoc.com',
      tags: ['Closed Won'],
      notes: 'Contract signed. Onboarding scheduled for next Monday.',
    },
  },
  {
    _id: 'conv_004',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98765 43210',
    lastMessage: 'Can you send me the pricing for the startup plan?',
    lastMessageTime: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
    unreadCount: 1,
    status: 'new',
    aiEnabled: true,
    assignedAdmin: null,
    customer: {
      customerName: 'Priya Sharma',
      customerPhone: '+91 98765 43210',
      businessName: 'NovaTech Solutions',
      email: 'priya@novatech.in',
      website: 'novatech.in',
      tags: ['Startup', 'Inbound'],
      notes: '',
    },
  },
  {
    _id: 'conv_005',
    customerName: 'James Wilson',
    customerPhone: '+44 7700 900123',
    lastMessage: 'I need to speak with a human agent please.',
    lastMessageTime: new Date(Date.now() - 7200000).toISOString(), // 2 hours ago
    unreadCount: 3,
    status: 'handoff',
    aiEnabled: false,
    assignedAdmin: { name: 'Alex' },
    customer: {
      customerName: 'James Wilson',
      customerPhone: '+44 7700 900123',
      businessName: 'Wilson Digital Ltd',
      email: 'james@wilsondigital.co.uk',
      website: 'wilsondigital.co.uk',
      tags: ['Escalation', 'UK'],
      notes: 'Customer frustrated with AI responses. Needs human support immediately.',
    },
  },
  {
    _id: 'conv_006',
    customerName: 'Ana Rodriguez',
    customerPhone: '+34 612 345 678',
    lastMessage: 'Muchas gracias! The integration is working now.',
    lastMessageTime: new Date(Date.now() - 4 * 86400000).toISOString(), // 4 days ago
    unreadCount: 0,
    status: 'open',
    aiEnabled: true,
    assignedAdmin: { name: 'Maria' },
    customer: {
      customerName: 'Ana Rodriguez',
      customerPhone: '+34 612 345 678',
      businessName: 'Rodriguez Marketing',
      email: 'ana@rodriguezmarketing.es',
      website: 'rodriguezmarketing.es',
      tags: ['Integration', 'Europe'],
      notes: 'API integration completed. Monitoring for any issues.',
    },
  },
];

export const dummyMessages = {
  conv_001: [
    {
      _id: 'msg_001',
      conversationId: 'conv_001',
      body: 'Hi there, I was looking at your enterprise CRM solutions and had a few questions about scaling for a team of 500.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    },
    {
      _id: 'msg_002',
      conversationId: 'conv_001',
      body: 'Hello Sarah! Thanks for reaching out. Our Enterprise plan is built exactly for teams of that size, featuring unlimited custom fields and advanced role-based access control. Would you like me to send over our scalability whitepaper?',
      sender: 'bot',
      direction: 'outbound',
      timestamp: new Date(Date.now() - 3600000 * 3 + 60000).toISOString(),
      status: 'read',
    },
    {
      _id: 'msg_003',
      conversationId: 'conv_001',
      body: 'That would be great. Also, what does the typical SLA look like? We need 99.99% uptime guaranteed.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      _id: 'msg_004',
      conversationId: 'conv_001',
      body: 'Here is the whitepaper. Regarding the SLA, our Enterprise tier includes a 99.99% financially backed uptime guarantee. I\'m tagging one of our enterprise specialists to discuss this further with you.',
      sender: 'bot',
      direction: 'outbound',
      timestamp: new Date(Date.now() - 3600000 * 2 + 60000).toISOString(),
      status: 'read',
    },
    {
      _id: 'msg_005',
      conversationId: 'conv_001',
      body: 'Yes, the enterprise plan looks perfect for our needs. Can we discuss the SLA in more detail?',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 1800000).toISOString(),
    },
  ],

  conv_002: [
    {
      _id: 'msg_010',
      conversationId: 'conv_002',
      body: 'Hi, we received the invoice for our subscription renewal. The amount seems higher than expected.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      _id: 'msg_011',
      conversationId: 'conv_002',
      body: 'Hello! I apologize for any confusion. The increase reflects the additional 50 user seats that were added to your plan last quarter. Would you like me to break down the charges?',
      sender: 'bot',
      direction: 'outbound',
      timestamp: new Date(Date.now() - 86400000 * 2 + 120000).toISOString(),
      status: 'delivered',
    },
    {
      _id: 'msg_012',
      conversationId: 'conv_002',
      body: 'Ah that makes sense. We will review the invoice and get back to you.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
    },
  ],

  conv_003: [
    {
      _id: 'msg_020',
      conversationId: 'conv_003',
      body: 'We\'ve finalized the contract on our end. Sending it over now.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
    {
      _id: 'msg_021',
      conversationId: 'conv_003',
      body: 'Wonderful, David! I\'ve received the signed contract. Our onboarding team will reach out within 24 hours to schedule your kickoff session. Welcome aboard! 🎉',
      sender: 'admin',
      direction: 'outbound',
      timestamp: new Date(Date.now() - 86400000 * 3 + 300000).toISOString(),
      status: 'read',
    },
    {
      _id: 'msg_022',
      conversationId: 'conv_003',
      body: 'Here is the signed contract.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
  ],

  conv_004: [
    {
      _id: 'msg_030',
      conversationId: 'conv_004',
      body: 'Hello! I discovered your product on ProductHunt. Looks really impressive.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      _id: 'msg_031',
      conversationId: 'conv_004',
      body: 'Thank you, Priya! We\'re glad you found us. We offer plans tailored for startups with flexible pricing. What size is your team currently?',
      sender: 'bot',
      direction: 'outbound',
      timestamp: new Date(Date.now() - 7200000 + 30000).toISOString(),
      status: 'read',
    },
    {
      _id: 'msg_032',
      conversationId: 'conv_004',
      body: 'We\'re a team of 12 right now but growing fast. Can you send me the pricing for the startup plan?',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
    },
  ],

  conv_005: [
    {
      _id: 'msg_040',
      conversationId: 'conv_005',
      body: 'Your bot keeps giving me irrelevant answers. I\'ve asked the same question 3 times now.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 10800000).toISOString(),
    },
    {
      _id: 'msg_041',
      conversationId: 'conv_005',
      body: 'I apologize for the inconvenience. Let me try to help you with your query. Could you please rephrase your question?',
      sender: 'bot',
      direction: 'outbound',
      timestamp: new Date(Date.now() - 10800000 + 15000).toISOString(),
      status: 'read',
    },
    {
      _id: 'msg_042',
      conversationId: 'conv_005',
      body: 'I need to speak with a human agent please. This is urgent.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      _id: 'msg_043',
      conversationId: 'conv_005',
      body: 'Hi James, this is Alex from the support team. I\'m here to help. I can see your previous messages — let me look into this for you right away.',
      sender: 'admin',
      direction: 'outbound',
      timestamp: new Date(Date.now() - 7200000 + 120000).toISOString(),
      status: 'delivered',
    },
  ],

  conv_006: [
    {
      _id: 'msg_050',
      conversationId: 'conv_006',
      body: 'Hola, estoy teniendo problemas con la integración de la API.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
    {
      _id: 'msg_051',
      conversationId: 'conv_006',
      body: 'Hi Ana! I\'d be happy to help with the API integration. Could you share the error message you\'re seeing? Also, which endpoint are you trying to connect to?',
      sender: 'bot',
      direction: 'outbound',
      timestamp: new Date(Date.now() - 86400000 * 5 + 45000).toISOString(),
      status: 'read',
    },
    {
      _id: 'msg_052',
      conversationId: 'conv_006',
      body: 'Muchas gracias! The integration is working now. The issue was with our auth token — it had expired.',
      sender: 'customer',
      direction: 'inbound',
      timestamp: new Date(Date.now() - 86400000 * 4).toISOString(),
    },
  ],
};
